/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Booker Platform API
 * API of the Booker hotel, the test object for the DeTesters Playwright training. Log in with `admin` / `password123` or `user` / `password123` and click Authorize.
 * OpenAPI spec version: 1.0.0
 */
import type { ValidationError } from './validationError';

/**
 * Validation failed. `details` maps each invalid field to a message.
 */
export type BadRequestResponse = ValidationError;
