/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Booker Platform API
 * API of the Booker hotel, the test object for the DeTesters Playwright training. Log in with `admin` / `password123` or `user` / `password123` and click Authorize.
 * OpenAPI spec version: 1.0.0
 */
import type { BookingStatus } from './bookingStatus';
import type { UserSummary } from './userSummary';
import type { Room } from './room';

export interface Booking {
  id: string;
  userId: string;
  roomId: string;
  checkIn: string;
  checkOut: string;
  status: BookingStatus;
  createdAt: string;
  updatedAt: string;
  user?: UserSummary;
  room?: Room;
}
