/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Booker Platform API
 * API of the Booker hotel, the test object for the DeTesters Playwright training. Log in with `admin` / `password123` or `user` / `password123` and click Authorize.
 * OpenAPI spec version: 1.0.0
 */
import type { BookingStatus } from './bookingStatus';
import type { Extra } from './extra';
import type { UserSummary } from './userSummary';
import type { Room } from './room';

export interface Booking {
  id: string;
  userId: string;
  roomId: string;
  checkIn: string;
  checkOut: string;
  status: BookingStatus;
  adults: number;
  children: number;
  extras: Extra[];
  /** Computed from checkIn and checkOut */
  nights: number;
  /** Computed; nights × room price + extras */
  totalPrice: number;
  createdAt: string;
  updatedAt: string;
  user?: UserSummary;
  room?: Room;
}
