/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Booker Platform API
 * API of the Booker hotel, the test object for the DeTesters Playwright training. Log in with `admin` / `password123` or `user` / `password123` and click Authorize.
 * OpenAPI spec version: 1.0.0
 */

export interface BrandingContact {
  /** @maxLength 100 */
  name?: string;
  /** @maxLength 200 */
  address?: string;
  /** @maxLength 50 */
  phone?: string;
  /** @maxLength 254 */
  email?: string;
}
