/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Booker Platform API
 * API of the Booker hotel, the test object for the DeTesters Playwright training. Log in with `admin` / `password123` or `user` / `password123` and click Authorize.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Breakfast: € 15 per guest per night · Parking: € 12 per night · Late check-out: € 25 per stay
 */
export type Extra = typeof Extra[keyof typeof Extra];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Extra = {
  BREAKFAST: 'BREAKFAST',
  PARKING: 'PARKING',
  LATE_CHECKOUT: 'LATE_CHECKOUT',
} as const;
