/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Booker Platform API
 * API of the Booker hotel, the test object for the DeTesters Playwright training. Log in with `admin` / `password123` or `user` / `password123` and click Authorize.
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiPublicRoomsTypeItem } from './getApiPublicRoomsTypeItem';
import type { GetApiPublicRoomsSort } from './getApiPublicRoomsSort';

export type GetApiPublicRoomsParams = {
/**
 * One or more room types, comma separated or repeated
 */
type?: GetApiPublicRoomsTypeItem[];
minPrice?: number;
maxPrice?: number;
/**
 * Minimum number of guests
 */
capacity?: number;
featured?: boolean;
checkIn?: string;
checkOut?: string;
sort?: GetApiPublicRoomsSort;
page?: number;
pageSize?: number;
};
