/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Booker Platform API
 * API of the Booker hotel, the test object for the DeTesters Playwright training. Log in with `admin` / `password123` or `user` / `password123` and click Authorize.
 * OpenAPI spec version: 1.0.0
 */
import type { MessageStatus } from './messageStatus';
import type { MessageUser } from './messageUser';

export interface Message {
  id: string;
  /**
   * `null` for messages sent with the public contact form
   * @nullable
   */
  userId: string | null;
  /**
   * Contact form only
   * @nullable
   */
  name: string | null;
  /**
   * Contact form only
   * @nullable
   */
  email: string | null;
  subject: string;
  content: string;
  status: MessageStatus;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  user?: MessageUser;
}
