/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Booker Platform API
 * API of the Booker hotel, the test object for the DeTesters Playwright training. Log in with `admin` / `password123` or `user` / `password123` and click Authorize.
 * OpenAPI spec version: 1.0.0
 */

export type PostApiAuthRegisterBody = {
  /**
   * @minLength 3
   * @maxLength 50
   * @pattern ^[A-Za-z0-9_.-]+$
   */
  username: string;
  email: string;
  /**
   * @minLength 8
   * @maxLength 100
   */
  password: string;
};
