/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Booker Platform API
 * API of the Booker hotel, the test object for the DeTesters Playwright training. Log in with `admin` / `password123` or `user` / `password123` and click Authorize.
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiReportsGenerateBodyType } from './postApiReportsGenerateBodyType';
import type { PostApiReportsGenerateBodyPeriod } from './postApiReportsGenerateBodyPeriod';

export type PostApiReportsGenerateBody = {
  type: PostApiReportsGenerateBodyType;
  period: PostApiReportsGenerateBodyPeriod;
};
