/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Booker Platform API
 * API of the Booker hotel, the test object for the DeTesters Playwright training. Log in with `admin` / `password123` or `user` / `password123` and click Authorize.
 * OpenAPI spec version: 1.0.0
 */
import type { RoomInput } from './roomInput';
import type { PostApiRoomsBodyAllOf } from './postApiRoomsBodyAllOf';

export type PostApiRoomsBody = RoomInput & PostApiRoomsBodyAllOf & Required<Pick<RoomInput & PostApiRoomsBodyAllOf, 'number' | 'type' | 'price' | 'capacity'>>;
