/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Booker Platform API
 * API of the Booker hotel, the test object for the DeTesters Playwright training. Log in with `admin` / `password123` or `user` / `password123` and click Authorize.
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiTestingSeedBodyUsersItem } from './postApiTestingSeedBodyUsersItem';
import type { PostApiTestingSeedBodyRoomsItem } from './postApiTestingSeedBodyRoomsItem';
import type { PostApiTestingSeedBodyBookingsItem } from './postApiTestingSeedBodyBookingsItem';

export type PostApiTestingSeedBody = {
  /** @pattern ^[A-Za-z0-9_]{1,30}$ */
  namespace: string;
  users?: PostApiTestingSeedBodyUsersItem[];
  rooms?: PostApiTestingSeedBodyRoomsItem[];
  bookings?: PostApiTestingSeedBodyBookingsItem[];
};
