/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Booker Platform API
 * API of the Booker hotel, the test object for the DeTesters Playwright training. Log in with `admin` / `password123` or `user` / `password123` and click Authorize.
 * OpenAPI spec version: 1.0.0
 */

export type PostApiTestingSeedBodyRoomsItemType = typeof PostApiTestingSeedBodyRoomsItemType[keyof typeof PostApiTestingSeedBodyRoomsItemType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiTestingSeedBodyRoomsItemType = {
  STANDARD: 'STANDARD',
  DELUXE: 'DELUXE',
  SUITE: 'SUITE',
} as const;
