/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Booker Platform API
 * API of the Booker hotel, the test object for the DeTesters Playwright training. Log in with `admin` / `password123` or `user` / `password123` and click Authorize.
 * OpenAPI spec version: 1.0.0
 */
import type { BrandingContact } from './brandingContact';
import type { BrandingMap } from './brandingMap';
import type { BrandingTheme } from './brandingTheme';

export interface PublicBranding {
  name: string;
  logoUrl: string;
  description: string;
  contact: BrandingContact;
  map: BrandingMap;
  theme: BrandingTheme;
}
