/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Booker Platform API
 * API of the Booker hotel, the test object for the DeTesters Playwright training. Log in with `admin` / `password123` or `user` / `password123` and click Authorize.
 * OpenAPI spec version: 1.0.0
 */

export type PutApiTestingFlagsBodyFlagsItem = typeof PutApiTestingFlagsBodyFlagsItem[keyof typeof PutApiTestingFlagsBodyFlagsItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutApiTestingFlagsBodyFlagsItem = {
  'slow-rooms': 'slow-rooms',
  'flaky-booking': 'flaky-booking',
  'stale-list': 'stale-list',
  'bug-a11y': 'bug-a11y',
  'bug-visual': 'bug-visual',
  'bug-price': 'bug-price',
  'bug-auth': 'bug-auth',
  'random-order': 'random-order',
  'popup-cookie': 'popup-cookie',
} as const;
