/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Booker Platform API
 * API of the Booker hotel, the test object for the DeTesters Playwright training. Log in with `admin` / `password123` or `user` / `password123` and click Authorize.
 * OpenAPI spec version: 1.0.0
 */

export type PutApiBookingsIdBodyStatus = typeof PutApiBookingsIdBodyStatus[keyof typeof PutApiBookingsIdBodyStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutApiBookingsIdBodyStatus = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
} as const;
