/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Booker Platform API
 * API of the Booker hotel, the test object for the DeTesters Playwright training. Log in with `admin` / `password123` or `user` / `password123` and click Authorize.
 * OpenAPI spec version: 1.0.0
 */
import type { ReportType } from './reportType';
import type { ReportData } from './reportData';
import type { ReportPeriod } from './reportPeriod';

export interface Report {
  id: string;
  type: ReportType;
  /** Report figures; the shape depends on the report type. */
  data: ReportData;
  period: ReportPeriod;
  generatedAt: string;
}
