/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Booker Platform API
 * API of the Booker hotel, the test object for the DeTesters Playwright training. Log in with `admin` / `password123` or `user` / `password123` and click Authorize.
 * OpenAPI spec version: 1.0.0
 */
import type { RoomType } from './roomType';
import type { RoomStatus } from './roomStatus';

export interface Room {
  id: string;
  number: string;
  type: RoomType;
  /** Price per night */
  price: number;
  capacity: number;
  amenities: string[];
  status: RoomStatus;
  /** Shown on the home page */
  featured: boolean;
  /**
   * Photo uploaded with `POST /api/rooms/{id}/image`
   * @nullable
   */
  imageUrl: string | null;
  /** Order in the admin room list; set with `PUT /api/rooms/order` */
  position: number;
  createdAt: string;
  updatedAt: string;
}
