/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Booker Platform API
 * API of the Booker hotel, the test object for the DeTesters Playwright training. Log in with `admin` / `password123` or `user` / `password123` and click Authorize.
 * OpenAPI spec version: 1.0.0
 */
import type { RoomInputType } from './roomInputType';
import type { RoomInputStatus } from './roomInputStatus';

export interface RoomInput {
  /** @maxLength 20 */
  number?: string;
  type?: RoomInputType;
  /** @minimum 0 */
  price?: number;
  /**
   * @minimum 1
   * @maximum 10
   */
  capacity?: number;
  amenities?: string[];
  status?: RoomInputStatus;
}
