/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Booker Platform API
 * API of the Booker hotel, the test object for the DeTesters Playwright training. Log in with `admin` / `password123` or `user` / `password123` and click Authorize.
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod';



/**
 * @summary Log in
 */
export const postApiAuthLoginBody = zod.object({
  "username": zod.string(),
  "password": zod.string()
})

export const postApiAuthLoginResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "token": zod.string(),
  "user": zod.object({
  "id": zod.string(),
  "username": zod.string(),
  "email": zod.string(),
  "role": zod.enum(['ROLE_USER', 'ROLE_ADMIN']),
  "createdAt": zod.string().datetime(),
  "updatedAt": zod.string().datetime()
})
})
})

/**
 * New users always get ROLE_USER. The response contains a token, so the user is logged in straight away.
 * @summary Register a new user
 */
export const postApiAuthRegisterBodyUsernameMin = 3;

export const postApiAuthRegisterBodyUsernameMax = 50;

export const postApiAuthRegisterBodyUsernameRegExp = new RegExp('^[A-Za-z0-9_.-]+$');
export const postApiAuthRegisterBodyPasswordMin = 8;

export const postApiAuthRegisterBodyPasswordMax = 100;


export const postApiAuthRegisterBody = zod.object({
  "username": zod.string().min(postApiAuthRegisterBodyUsernameMin).max(postApiAuthRegisterBodyUsernameMax).regex(postApiAuthRegisterBodyUsernameRegExp),
  "email": zod.string().email(),
  "password": zod.string().min(postApiAuthRegisterBodyPasswordMin).max(postApiAuthRegisterBodyPasswordMax)
})

/**
 * Tokens are stateless JWTs, so logging out only tells the client to forget its token.
 * @summary Log out
 */
export const postApiAuthLogoutResponse = zod.object({
  "success": zod.boolean()
})

