/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Booker Platform API
 * API of the Booker hotel, the test object for the DeTesters Playwright training. Log in with `admin` / `password123` or `user` / `password123` and click Authorize.
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod';



/**
 * @summary List all bookings (admin only)
 */
export const getApiBookingsResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.array(zod.object({
  "id": zod.string(),
  "userId": zod.string(),
  "roomId": zod.string(),
  "checkIn": zod.string().datetime(),
  "checkOut": zod.string().datetime(),
  "status": zod.enum(['PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED']),
  "createdAt": zod.string().datetime(),
  "updatedAt": zod.string().datetime(),
  "user": zod.object({
  "id": zod.string(),
  "username": zod.string(),
  "email": zod.string()
}).optional(),
  "room": zod.object({
  "id": zod.string(),
  "number": zod.string(),
  "type": zod.enum(['STANDARD', 'DELUXE', 'SUITE']),
  "price": zod.number().describe('Price per night'),
  "capacity": zod.number(),
  "amenities": zod.array(zod.string()),
  "status": zod.enum(['AVAILABLE', 'OCCUPIED', 'MAINTENANCE']),
  "createdAt": zod.string().datetime(),
  "updatedAt": zod.string().datetime()
}).optional()
}))
})

/**
 * Creates a PENDING booking for the logged-in user.
- `checkIn` may not be in the past and `checkOut` must be after `checkIn` (400).
- The room must exist (404) and not be in MAINTENANCE (409).
- The dates may not overlap a PENDING or CONFIRMED booking for the same room (409 `Room not available`).
  Checking out on the day the next guest checks in is fine.

 * @summary Book a room
 */
export const postApiBookingsBody = zod.object({
  "roomId": zod.string(),
  "checkIn": zod.string().datetime(),
  "checkOut": zod.string().datetime()
})

/**
 * @summary List the bookings of the logged-in user
 */
export const getApiBookingsMyBookingsResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.array(zod.object({
  "id": zod.string(),
  "userId": zod.string(),
  "roomId": zod.string(),
  "checkIn": zod.string().datetime(),
  "checkOut": zod.string().datetime(),
  "status": zod.enum(['PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED']),
  "createdAt": zod.string().datetime(),
  "updatedAt": zod.string().datetime(),
  "user": zod.object({
  "id": zod.string(),
  "username": zod.string(),
  "email": zod.string()
}).optional(),
  "room": zod.object({
  "id": zod.string(),
  "number": zod.string(),
  "type": zod.enum(['STANDARD', 'DELUXE', 'SUITE']),
  "price": zod.number().describe('Price per night'),
  "capacity": zod.number(),
  "amenities": zod.array(zod.string()),
  "status": zod.enum(['AVAILABLE', 'OCCUPIED', 'MAINTENANCE']),
  "createdAt": zod.string().datetime(),
  "updatedAt": zod.string().datetime()
}).optional()
}))
})

/**
 * Only the owner of the booking or an admin may read it.
 * @summary Get a booking
 */
export const getApiBookingsIdResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "id": zod.string(),
  "userId": zod.string(),
  "roomId": zod.string(),
  "checkIn": zod.string().datetime(),
  "checkOut": zod.string().datetime(),
  "status": zod.enum(['PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED']),
  "createdAt": zod.string().datetime(),
  "updatedAt": zod.string().datetime(),
  "user": zod.object({
  "id": zod.string(),
  "username": zod.string(),
  "email": zod.string()
}).optional(),
  "room": zod.object({
  "id": zod.string(),
  "number": zod.string(),
  "type": zod.enum(['STANDARD', 'DELUXE', 'SUITE']),
  "price": zod.number().describe('Price per night'),
  "capacity": zod.number(),
  "amenities": zod.array(zod.string()),
  "status": zod.enum(['AVAILABLE', 'OCCUPIED', 'MAINTENANCE']),
  "createdAt": zod.string().datetime(),
  "updatedAt": zod.string().datetime()
}).optional()
})
})

/**
 * @summary Change the status of a booking (admin only)
 */
export const putApiBookingsIdBody = zod.object({
  "status": zod.enum(['PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED'])
})

export const putApiBookingsIdResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "id": zod.string(),
  "userId": zod.string(),
  "roomId": zod.string(),
  "checkIn": zod.string().datetime(),
  "checkOut": zod.string().datetime(),
  "status": zod.enum(['PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED']),
  "createdAt": zod.string().datetime(),
  "updatedAt": zod.string().datetime(),
  "user": zod.object({
  "id": zod.string(),
  "username": zod.string(),
  "email": zod.string()
}).optional(),
  "room": zod.object({
  "id": zod.string(),
  "number": zod.string(),
  "type": zod.enum(['STANDARD', 'DELUXE', 'SUITE']),
  "price": zod.number().describe('Price per night'),
  "capacity": zod.number(),
  "amenities": zod.array(zod.string()),
  "status": zod.enum(['AVAILABLE', 'OCCUPIED', 'MAINTENANCE']),
  "createdAt": zod.string().datetime(),
  "updatedAt": zod.string().datetime()
}).optional()
})
})

/**
 * Sets the status to CANCELLED. Only the owner of the booking or an admin may cancel it.
 * @summary Cancel a booking
 */
export const deleteApiBookingsIdResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string()
})

