/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Booker Platform API
 * API of the Booker hotel, the test object for the DeTesters Playwright training. Log in with `admin` / `password123` or `user` / `password123` and click Authorize.
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod';



/**
 * @summary List all bookings (admin only)
 */
export const getApiBookingsResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.array(zod.object({
  "id": zod.string(),
  "userId": zod.string(),
  "roomId": zod.string(),
  "checkIn": zod.string().datetime(),
  "checkOut": zod.string().datetime(),
  "status": zod.enum(['PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED']),
  "adults": zod.number(),
  "children": zod.number(),
  "extras": zod.array(zod.enum(['BREAKFAST', 'PARKING', 'LATE_CHECKOUT']).describe('Breakfast: € 15 per guest per night · Parking: € 12 per night · Late check-out: € 25 per stay')),
  "nights": zod.number().describe('Computed from checkIn and checkOut'),
  "totalPrice": zod.number().describe('Computed; nights × room price + extras'),
  "createdAt": zod.string().datetime(),
  "updatedAt": zod.string().datetime(),
  "user": zod.object({
  "id": zod.string(),
  "username": zod.string(),
  "email": zod.string()
}).optional(),
  "room": zod.object({
  "id": zod.string(),
  "number": zod.string(),
  "type": zod.enum(['STANDARD', 'DELUXE', 'SUITE']),
  "price": zod.number().describe('Price per night'),
  "capacity": zod.number(),
  "amenities": zod.array(zod.string()),
  "status": zod.enum(['AVAILABLE', 'OCCUPIED', 'MAINTENANCE']),
  "featured": zod.boolean().describe('Shown on the home page'),
  "createdAt": zod.string().datetime(),
  "updatedAt": zod.string().datetime()
}).optional()
}))
})

/**
 * Creates a PENDING booking for the logged-in user.
- `checkIn` may not be in the past and `checkOut` must be after `checkIn` (400).
- The room must exist (404) and not be in MAINTENANCE (409).
- The dates may not overlap a PENDING or CONFIRMED booking for the same room (409 `Room not available`).
  Checking out on the day the next guest checks in is fine.
- `adults` (default 1) + `children` (default 0) may not exceed the room capacity (400, `details.guests`).
- `nights` and `totalPrice` are computed by the server.

 * @summary Book a room
 */
export const postApiBookingsBodyAdultsDefault = 1;
export const postApiBookingsBodyAdultsMax = 10;
export const postApiBookingsBodyChildrenDefault = 0;
export const postApiBookingsBodyChildrenMin = 0;

export const postApiBookingsBodyChildrenMax = 10;


export const postApiBookingsBody = zod.object({
  "roomId": zod.string(),
  "checkIn": zod.string().datetime(),
  "checkOut": zod.string().datetime(),
  "adults": zod.number().min(1).max(postApiBookingsBodyAdultsMax).default(postApiBookingsBodyAdultsDefault),
  "children": zod.number().min(postApiBookingsBodyChildrenMin).max(postApiBookingsBodyChildrenMax).optional(),
  "extras": zod.array(zod.enum(['BREAKFAST', 'PARKING', 'LATE_CHECKOUT']).describe('Breakfast: € 15 per guest per night · Parking: € 12 per night · Late check-out: € 25 per stay')).optional()
})

/**
 * @summary List the bookings of the logged-in user
 */
export const getApiBookingsMyBookingsResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.array(zod.object({
  "id": zod.string(),
  "userId": zod.string(),
  "roomId": zod.string(),
  "checkIn": zod.string().datetime(),
  "checkOut": zod.string().datetime(),
  "status": zod.enum(['PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED']),
  "adults": zod.number(),
  "children": zod.number(),
  "extras": zod.array(zod.enum(['BREAKFAST', 'PARKING', 'LATE_CHECKOUT']).describe('Breakfast: € 15 per guest per night · Parking: € 12 per night · Late check-out: € 25 per stay')),
  "nights": zod.number().describe('Computed from checkIn and checkOut'),
  "totalPrice": zod.number().describe('Computed; nights × room price + extras'),
  "createdAt": zod.string().datetime(),
  "updatedAt": zod.string().datetime(),
  "user": zod.object({
  "id": zod.string(),
  "username": zod.string(),
  "email": zod.string()
}).optional(),
  "room": zod.object({
  "id": zod.string(),
  "number": zod.string(),
  "type": zod.enum(['STANDARD', 'DELUXE', 'SUITE']),
  "price": zod.number().describe('Price per night'),
  "capacity": zod.number(),
  "amenities": zod.array(zod.string()),
  "status": zod.enum(['AVAILABLE', 'OCCUPIED', 'MAINTENANCE']),
  "featured": zod.boolean().describe('Shown on the home page'),
  "createdAt": zod.string().datetime(),
  "updatedAt": zod.string().datetime()
}).optional()
}))
})

/**
 * Only the owner of the booking or an admin may read it.
 * @summary Get a booking
 */
export const getApiBookingsIdResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "id": zod.string(),
  "userId": zod.string(),
  "roomId": zod.string(),
  "checkIn": zod.string().datetime(),
  "checkOut": zod.string().datetime(),
  "status": zod.enum(['PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED']),
  "adults": zod.number(),
  "children": zod.number(),
  "extras": zod.array(zod.enum(['BREAKFAST', 'PARKING', 'LATE_CHECKOUT']).describe('Breakfast: € 15 per guest per night · Parking: € 12 per night · Late check-out: € 25 per stay')),
  "nights": zod.number().describe('Computed from checkIn and checkOut'),
  "totalPrice": zod.number().describe('Computed; nights × room price + extras'),
  "createdAt": zod.string().datetime(),
  "updatedAt": zod.string().datetime(),
  "user": zod.object({
  "id": zod.string(),
  "username": zod.string(),
  "email": zod.string()
}).optional(),
  "room": zod.object({
  "id": zod.string(),
  "number": zod.string(),
  "type": zod.enum(['STANDARD', 'DELUXE', 'SUITE']),
  "price": zod.number().describe('Price per night'),
  "capacity": zod.number(),
  "amenities": zod.array(zod.string()),
  "status": zod.enum(['AVAILABLE', 'OCCUPIED', 'MAINTENANCE']),
  "featured": zod.boolean().describe('Shown on the home page'),
  "createdAt": zod.string().datetime(),
  "updatedAt": zod.string().datetime()
}).optional()
})
})

/**
 * @summary Change the status of a booking (admin only)
 */
export const putApiBookingsIdBody = zod.object({
  "status": zod.enum(['PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED'])
})

export const putApiBookingsIdResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "id": zod.string(),
  "userId": zod.string(),
  "roomId": zod.string(),
  "checkIn": zod.string().datetime(),
  "checkOut": zod.string().datetime(),
  "status": zod.enum(['PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED']),
  "adults": zod.number(),
  "children": zod.number(),
  "extras": zod.array(zod.enum(['BREAKFAST', 'PARKING', 'LATE_CHECKOUT']).describe('Breakfast: € 15 per guest per night · Parking: € 12 per night · Late check-out: € 25 per stay')),
  "nights": zod.number().describe('Computed from checkIn and checkOut'),
  "totalPrice": zod.number().describe('Computed; nights × room price + extras'),
  "createdAt": zod.string().datetime(),
  "updatedAt": zod.string().datetime(),
  "user": zod.object({
  "id": zod.string(),
  "username": zod.string(),
  "email": zod.string()
}).optional(),
  "room": zod.object({
  "id": zod.string(),
  "number": zod.string(),
  "type": zod.enum(['STANDARD', 'DELUXE', 'SUITE']),
  "price": zod.number().describe('Price per night'),
  "capacity": zod.number(),
  "amenities": zod.array(zod.string()),
  "status": zod.enum(['AVAILABLE', 'OCCUPIED', 'MAINTENANCE']),
  "featured": zod.boolean().describe('Shown on the home page'),
  "createdAt": zod.string().datetime(),
  "updatedAt": zod.string().datetime()
}).optional()
})
})

/**
 * Sets the status to CANCELLED. Only the owner of the booking or an admin may cancel it.
 * @summary Cancel a booking
 */
export const deleteApiBookingsIdResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string()
})

