/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Booker Platform API
 * API of the Booker hotel, the test object for the DeTesters Playwright training. Log in with `admin` / `password123` or `user` / `password123` and click Authorize.
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod';



/**
 * @summary Get the hotel branding
 */
export const getApiBrandingResponseDataContactNameMax = 100;
export const getApiBrandingResponseDataContactAddressMax = 200;
export const getApiBrandingResponseDataContactPhoneMax = 50;
export const getApiBrandingResponseDataContactEmailMax = 254;
export const getApiBrandingResponseDataMapLatitudeMin = -90;

export const getApiBrandingResponseDataMapLatitudeMax = 90;
export const getApiBrandingResponseDataMapLongitudeMin = -180;

export const getApiBrandingResponseDataMapLongitudeMax = 180;
export const getApiBrandingResponseDataThemePrimaryColorRegExp = new RegExp('^#[0-9A-Fa-f]{6}$');
export const getApiBrandingResponseDataThemeSecondaryColorRegExp = new RegExp('^#[0-9A-Fa-f]{6}$');


export const getApiBrandingResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "logoUrl": zod.string(),
  "description": zod.string(),
  "contact": zod.object({
  "name": zod.string().max(getApiBrandingResponseDataContactNameMax).optional(),
  "address": zod.string().max(getApiBrandingResponseDataContactAddressMax).optional(),
  "phone": zod.string().max(getApiBrandingResponseDataContactPhoneMax).optional(),
  "email": zod.string().max(getApiBrandingResponseDataContactEmailMax).optional()
}),
  "map": zod.object({
  "latitude": zod.number().min(getApiBrandingResponseDataMapLatitudeMin).max(getApiBrandingResponseDataMapLatitudeMax).optional(),
  "longitude": zod.number().min(getApiBrandingResponseDataMapLongitudeMin).max(getApiBrandingResponseDataMapLongitudeMax).optional()
}),
  "theme": zod.object({
  "primaryColor": zod.string().regex(getApiBrandingResponseDataThemePrimaryColorRegExp).optional(),
  "secondaryColor": zod.string().regex(getApiBrandingResponseDataThemeSecondaryColorRegExp).optional()
}),
  "createdAt": zod.string().datetime(),
  "updatedAt": zod.string().datetime()
})
})

/**
 * @summary Update the hotel branding (admin only)
 */
export const putApiBrandingBodyNameMax = 100;
export const putApiBrandingBodyLogoUrlMax = 500;
export const putApiBrandingBodyDescriptionMax = 1000;
export const putApiBrandingBodyContactNameMax = 100;
export const putApiBrandingBodyContactAddressMax = 200;
export const putApiBrandingBodyContactPhoneMax = 50;
export const putApiBrandingBodyContactEmailMax = 254;
export const putApiBrandingBodyMapLatitudeMin = -90;

export const putApiBrandingBodyMapLatitudeMax = 90;
export const putApiBrandingBodyMapLongitudeMin = -180;

export const putApiBrandingBodyMapLongitudeMax = 180;
export const putApiBrandingBodyThemePrimaryColorRegExp = new RegExp('^#[0-9A-Fa-f]{6}$');
export const putApiBrandingBodyThemeSecondaryColorRegExp = new RegExp('^#[0-9A-Fa-f]{6}$');


export const putApiBrandingBody = zod.object({
  "name": zod.string().max(putApiBrandingBodyNameMax).optional(),
  "logoUrl": zod.string().max(putApiBrandingBodyLogoUrlMax).optional(),
  "description": zod.string().max(putApiBrandingBodyDescriptionMax).optional(),
  "contact": zod.object({
  "name": zod.string().max(putApiBrandingBodyContactNameMax).optional(),
  "address": zod.string().max(putApiBrandingBodyContactAddressMax).optional(),
  "phone": zod.string().max(putApiBrandingBodyContactPhoneMax).optional(),
  "email": zod.string().max(putApiBrandingBodyContactEmailMax).optional()
}).optional(),
  "map": zod.object({
  "latitude": zod.number().min(putApiBrandingBodyMapLatitudeMin).max(putApiBrandingBodyMapLatitudeMax).optional(),
  "longitude": zod.number().min(putApiBrandingBodyMapLongitudeMin).max(putApiBrandingBodyMapLongitudeMax).optional()
}).optional(),
  "theme": zod.object({
  "primaryColor": zod.string().regex(putApiBrandingBodyThemePrimaryColorRegExp).optional(),
  "secondaryColor": zod.string().regex(putApiBrandingBodyThemeSecondaryColorRegExp).optional()
}).optional()
}).describe('Every field is optional; nested objects are merged with the current branding.')

export const putApiBrandingResponseDataContactNameMax = 100;
export const putApiBrandingResponseDataContactAddressMax = 200;
export const putApiBrandingResponseDataContactPhoneMax = 50;
export const putApiBrandingResponseDataContactEmailMax = 254;
export const putApiBrandingResponseDataMapLatitudeMin = -90;

export const putApiBrandingResponseDataMapLatitudeMax = 90;
export const putApiBrandingResponseDataMapLongitudeMin = -180;

export const putApiBrandingResponseDataMapLongitudeMax = 180;
export const putApiBrandingResponseDataThemePrimaryColorRegExp = new RegExp('^#[0-9A-Fa-f]{6}$');
export const putApiBrandingResponseDataThemeSecondaryColorRegExp = new RegExp('^#[0-9A-Fa-f]{6}$');


export const putApiBrandingResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "logoUrl": zod.string(),
  "description": zod.string(),
  "contact": zod.object({
  "name": zod.string().max(putApiBrandingResponseDataContactNameMax).optional(),
  "address": zod.string().max(putApiBrandingResponseDataContactAddressMax).optional(),
  "phone": zod.string().max(putApiBrandingResponseDataContactPhoneMax).optional(),
  "email": zod.string().max(putApiBrandingResponseDataContactEmailMax).optional()
}),
  "map": zod.object({
  "latitude": zod.number().min(putApiBrandingResponseDataMapLatitudeMin).max(putApiBrandingResponseDataMapLatitudeMax).optional(),
  "longitude": zod.number().min(putApiBrandingResponseDataMapLongitudeMin).max(putApiBrandingResponseDataMapLongitudeMax).optional()
}),
  "theme": zod.object({
  "primaryColor": zod.string().regex(putApiBrandingResponseDataThemePrimaryColorRegExp).optional(),
  "secondaryColor": zod.string().regex(putApiBrandingResponseDataThemeSecondaryColorRegExp).optional()
}),
  "createdAt": zod.string().datetime(),
  "updatedAt": zod.string().datetime()
})
})

/**
 * @summary Restore the default branding (admin only)
 */
export const postApiBrandingResetResponseDataContactNameMax = 100;
export const postApiBrandingResetResponseDataContactAddressMax = 200;
export const postApiBrandingResetResponseDataContactPhoneMax = 50;
export const postApiBrandingResetResponseDataContactEmailMax = 254;
export const postApiBrandingResetResponseDataMapLatitudeMin = -90;

export const postApiBrandingResetResponseDataMapLatitudeMax = 90;
export const postApiBrandingResetResponseDataMapLongitudeMin = -180;

export const postApiBrandingResetResponseDataMapLongitudeMax = 180;
export const postApiBrandingResetResponseDataThemePrimaryColorRegExp = new RegExp('^#[0-9A-Fa-f]{6}$');
export const postApiBrandingResetResponseDataThemeSecondaryColorRegExp = new RegExp('^#[0-9A-Fa-f]{6}$');


export const postApiBrandingResetResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "logoUrl": zod.string(),
  "description": zod.string(),
  "contact": zod.object({
  "name": zod.string().max(postApiBrandingResetResponseDataContactNameMax).optional(),
  "address": zod.string().max(postApiBrandingResetResponseDataContactAddressMax).optional(),
  "phone": zod.string().max(postApiBrandingResetResponseDataContactPhoneMax).optional(),
  "email": zod.string().max(postApiBrandingResetResponseDataContactEmailMax).optional()
}),
  "map": zod.object({
  "latitude": zod.number().min(postApiBrandingResetResponseDataMapLatitudeMin).max(postApiBrandingResetResponseDataMapLatitudeMax).optional(),
  "longitude": zod.number().min(postApiBrandingResetResponseDataMapLongitudeMin).max(postApiBrandingResetResponseDataMapLongitudeMax).optional()
}),
  "theme": zod.object({
  "primaryColor": zod.string().regex(postApiBrandingResetResponseDataThemePrimaryColorRegExp).optional(),
  "secondaryColor": zod.string().regex(postApiBrandingResetResponseDataThemeSecondaryColorRegExp).optional()
}),
  "createdAt": zod.string().datetime(),
  "updatedAt": zod.string().datetime()
})
})

