/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Booker Platform API
 * API of the Booker hotel, the test object for the DeTesters Playwright training. Log in with `admin` / `password123` or `user` / `password123` and click Authorize.
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod';



/**
 * A `text/event-stream` that stays open. `EventSource` cannot send headers, so pass the token as `?token=`
(an `Authorization` header works too). Events:

- `ready`: sent once after connecting
- `booking.created`, `booking.updated`: `{ id, status, roomNumber, checkIn, checkOut, username, actor }` (`actor`: who made the change); sent to the guest of the booking and to admins
- `message.created`: `{ id, subject, from }`; admins only

 * @summary Live updates (Server-Sent Events)
 */
export const getApiEventsQueryParams = zod.object({
  "token": zod.string().optional().describe('JWT from `/api/auth/login`')
})

