/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Booker Platform API
 * API of the Booker hotel, the test object for the DeTesters Playwright training. Log in with `admin` / `password123` or `user` / `password123` and click Authorize.
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod';



/**
 * @summary List all messages (admin only)
 */
export const getApiMessagesResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.array(zod.object({
  "id": zod.string(),
  "userId": zod.string().nullable().describe('`null` for messages sent with the public contact form'),
  "name": zod.string().nullable().describe('Contact form only'),
  "email": zod.string().nullable().describe('Contact form only'),
  "subject": zod.string(),
  "content": zod.string(),
  "status": zod.enum(['UNREAD', 'READ', 'ARCHIVED']),
  "createdAt": zod.string().datetime(),
  "updatedAt": zod.string().datetime(),
  "user": zod.object({
  "id": zod.string(),
  "username": zod.string(),
  "email": zod.string()
}).nullish()
}))
})

/**
 * @summary Send a message to the hotel
 */
export const postApiMessagesBodySubjectMax = 200;
export const postApiMessagesBodyContentMax = 5000;


export const postApiMessagesBody = zod.object({
  "subject": zod.string().max(postApiMessagesBodySubjectMax),
  "content": zod.string().max(postApiMessagesBodyContentMax)
})

/**
 * @summary List the messages of the logged-in user
 */
export const getApiMessagesMyMessagesResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.array(zod.object({
  "id": zod.string(),
  "userId": zod.string().nullable().describe('`null` for messages sent with the public contact form'),
  "name": zod.string().nullable().describe('Contact form only'),
  "email": zod.string().nullable().describe('Contact form only'),
  "subject": zod.string(),
  "content": zod.string(),
  "status": zod.enum(['UNREAD', 'READ', 'ARCHIVED']),
  "createdAt": zod.string().datetime(),
  "updatedAt": zod.string().datetime(),
  "user": zod.object({
  "id": zod.string(),
  "username": zod.string(),
  "email": zod.string()
}).nullish()
}))
})

/**
 * Only the sender or an admin may read it.
 * @summary Get a message
 */
export const getApiMessagesIdResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "id": zod.string(),
  "userId": zod.string().nullable().describe('`null` for messages sent with the public contact form'),
  "name": zod.string().nullable().describe('Contact form only'),
  "email": zod.string().nullable().describe('Contact form only'),
  "subject": zod.string(),
  "content": zod.string(),
  "status": zod.enum(['UNREAD', 'READ', 'ARCHIVED']),
  "createdAt": zod.string().datetime(),
  "updatedAt": zod.string().datetime(),
  "user": zod.object({
  "id": zod.string(),
  "username": zod.string(),
  "email": zod.string()
}).nullish()
})
})

/**
 * @summary Change the status of a message (admin only)
 */
export const putApiMessagesIdBody = zod.object({
  "status": zod.enum(['UNREAD', 'READ', 'ARCHIVED'])
})

export const putApiMessagesIdResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "id": zod.string(),
  "userId": zod.string().nullable().describe('`null` for messages sent with the public contact form'),
  "name": zod.string().nullable().describe('Contact form only'),
  "email": zod.string().nullable().describe('Contact form only'),
  "subject": zod.string(),
  "content": zod.string(),
  "status": zod.enum(['UNREAD', 'READ', 'ARCHIVED']),
  "createdAt": zod.string().datetime(),
  "updatedAt": zod.string().datetime(),
  "user": zod.object({
  "id": zod.string(),
  "username": zod.string(),
  "email": zod.string()
}).nullish()
})
})

/**
 * @summary Delete a message (admin only)
 */
export const deleteApiMessagesIdResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string()
})

