/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Booker Platform API
 * API of the Booker hotel, the test object for the DeTesters Playwright training. Log in with `admin` / `password123` or `user` / `password123` and click Authorize.
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod';



/**
 * Filters can be combined. Passing `checkIn` and `checkOut` only returns rooms that are available
for the whole period (not in maintenance, no overlapping pending or confirmed booking).

 * @summary Search rooms (no token needed)
 */
export const getApiPublicRoomsQueryMinPriceMin = 0;
export const getApiPublicRoomsQueryMaxPriceMin = 0;
export const getApiPublicRoomsQuerySortDefault = "number";export const getApiPublicRoomsQueryPageDefault = 1;export const getApiPublicRoomsQueryPageSizeDefault = 6;
export const getApiPublicRoomsQueryPageSizeMax = 50;


export const getApiPublicRoomsQueryParams = zod.object({
  "type": zod.array(zod.enum(['STANDARD', 'DELUXE', 'SUITE'])).optional().describe('One or more room types, comma separated or repeated'),
  "minPrice": zod.number().min(getApiPublicRoomsQueryMinPriceMin).optional(),
  "maxPrice": zod.number().min(getApiPublicRoomsQueryMaxPriceMin).optional(),
  "capacity": zod.number().min(1).optional().describe('Minimum number of guests'),
  "featured": zod.boolean().optional(),
  "checkIn": zod.string().date().optional(),
  "checkOut": zod.string().date().optional(),
  "sort": zod.enum(['number', 'price', '-price', 'capacity', '-capacity']).default(getApiPublicRoomsQuerySortDefault),
  "page": zod.number().min(1).default(getApiPublicRoomsQueryPageDefault),
  "pageSize": zod.number().min(1).max(getApiPublicRoomsQueryPageSizeMax).default(getApiPublicRoomsQueryPageSizeDefault)
})

export const getApiPublicRoomsResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.array(zod.object({
  "id": zod.string(),
  "number": zod.string(),
  "type": zod.enum(['STANDARD', 'DELUXE', 'SUITE']),
  "price": zod.number().describe('Price per night'),
  "capacity": zod.number(),
  "amenities": zod.array(zod.string()),
  "status": zod.enum(['AVAILABLE', 'OCCUPIED', 'MAINTENANCE']),
  "featured": zod.boolean().describe('Shown on the home page'),
  "imageUrl": zod.string().nullable().describe('Photo uploaded with `POST /api/rooms/{id}/image`'),
  "position": zod.number().describe('Order in the admin room list; set with `PUT /api/rooms/order`'),
  "createdAt": zod.string().datetime(),
  "updatedAt": zod.string().datetime()
})),
  "meta": zod.object({
  "page": zod.number(),
  "pageSize": zod.number(),
  "total": zod.number(),
  "totalPages": zod.number()
})
})

/**
 * @summary Get a room by id or room number (no token needed)
 */
export const getApiPublicRoomsIdParams = zod.object({
  "id": zod.string().describe('Room id or room number, for example `101`')
})

export const getApiPublicRoomsIdResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "id": zod.string(),
  "number": zod.string(),
  "type": zod.enum(['STANDARD', 'DELUXE', 'SUITE']),
  "price": zod.number().describe('Price per night'),
  "capacity": zod.number(),
  "amenities": zod.array(zod.string()),
  "status": zod.enum(['AVAILABLE', 'OCCUPIED', 'MAINTENANCE']),
  "featured": zod.boolean().describe('Shown on the home page'),
  "imageUrl": zod.string().nullable().describe('Photo uploaded with `POST /api/rooms/{id}/image`'),
  "position": zod.number().describe('Order in the admin room list; set with `PUT /api/rooms/order`'),
  "createdAt": zod.string().datetime(),
  "updatedAt": zod.string().datetime()
}).and(zod.object({
  "bookedPeriods": zod.array(zod.object({
  "checkIn": zod.string().datetime(),
  "checkOut": zod.string().datetime()
})).describe('Pending and confirmed bookings that have not ended yet')
}))
})

/**
 * @summary Get the hotel branding (no token needed)
 */
export const getApiPublicBrandingResponseDataContactNameMax = 100;
export const getApiPublicBrandingResponseDataContactAddressMax = 200;
export const getApiPublicBrandingResponseDataContactPhoneMax = 50;
export const getApiPublicBrandingResponseDataContactEmailMax = 254;
export const getApiPublicBrandingResponseDataMapLatitudeMin = -90;

export const getApiPublicBrandingResponseDataMapLatitudeMax = 90;
export const getApiPublicBrandingResponseDataMapLongitudeMin = -180;

export const getApiPublicBrandingResponseDataMapLongitudeMax = 180;
export const getApiPublicBrandingResponseDataThemePrimaryColorRegExp = new RegExp('^#[0-9A-Fa-f]{6}$');
export const getApiPublicBrandingResponseDataThemeSecondaryColorRegExp = new RegExp('^#[0-9A-Fa-f]{6}$');


export const getApiPublicBrandingResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "name": zod.string(),
  "logoUrl": zod.string(),
  "description": zod.string(),
  "contact": zod.object({
  "name": zod.string().max(getApiPublicBrandingResponseDataContactNameMax).optional(),
  "address": zod.string().max(getApiPublicBrandingResponseDataContactAddressMax).optional(),
  "phone": zod.string().max(getApiPublicBrandingResponseDataContactPhoneMax).optional(),
  "email": zod.string().max(getApiPublicBrandingResponseDataContactEmailMax).optional()
}),
  "map": zod.object({
  "latitude": zod.number().min(getApiPublicBrandingResponseDataMapLatitudeMin).max(getApiPublicBrandingResponseDataMapLatitudeMax).optional(),
  "longitude": zod.number().min(getApiPublicBrandingResponseDataMapLongitudeMin).max(getApiPublicBrandingResponseDataMapLongitudeMax).optional()
}),
  "theme": zod.object({
  "primaryColor": zod.string().regex(getApiPublicBrandingResponseDataThemePrimaryColorRegExp).optional(),
  "secondaryColor": zod.string().regex(getApiPublicBrandingResponseDataThemeSecondaryColorRegExp).optional()
})
})
})

/**
 * @summary Send a message with the contact form (no token needed)
 */
export const postApiPublicMessagesBodyNameMax = 100;
export const postApiPublicMessagesBodySubjectMax = 200;
export const postApiPublicMessagesBodyContentMax = 5000;


export const postApiPublicMessagesBody = zod.object({
  "name": zod.string().max(postApiPublicMessagesBodyNameMax),
  "email": zod.string().email(),
  "subject": zod.string().max(postApiPublicMessagesBodySubjectMax),
  "content": zod.string().max(postApiPublicMessagesBodyContentMax)
})

/**
 * Runtime flags plus the `x-booker-flags` request header. Always empty when the test API is off. The web UI reads them on start-up.
 * @summary Trainer flags that apply to this request
 */
export const getApiPublicFlagsResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "enabled": zod.array(zod.string())
})
})

