/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Booker Platform API
 * API of the Booker hotel, the test object for the DeTesters Playwright training. Log in with `admin` / `password123` or `user` / `password123` and click Authorize.
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod';



/**
 * @summary List all reports (admin only)
 */
export const getApiReportsResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.array(zod.object({
  "id": zod.string(),
  "type": zod.enum(['OCCUPANCY', 'REVENUE', 'CUSTOMER_SATISFACTION']),
  "data": zod.record(zod.string(), zod.any()).describe('Report figures; the shape depends on the report type.'),
  "period": zod.object({
  "start": zod.string().datetime(),
  "end": zod.string().datetime()
}),
  "generatedAt": zod.string().datetime()
}))
})

/**
 * The report figures are sample data.
 * @summary Generate a report (admin only)
 */
export const postApiReportsGenerateBody = zod.object({
  "type": zod.enum(['OCCUPANCY', 'REVENUE', 'CUSTOMER_SATISFACTION']),
  "period": zod.object({
  "start": zod.string().datetime(),
  "end": zod.string().datetime()
})
})

/**
 * @summary Get a report (admin only)
 */
export const getApiReportsIdResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "id": zod.string(),
  "type": zod.enum(['OCCUPANCY', 'REVENUE', 'CUSTOMER_SATISFACTION']),
  "data": zod.record(zod.string(), zod.any()).describe('Report figures; the shape depends on the report type.'),
  "period": zod.object({
  "start": zod.string().datetime(),
  "end": zod.string().datetime()
}),
  "generatedAt": zod.string().datetime()
})
})

/**
 * @summary Delete a report (admin only)
 */
export const deleteApiReportsIdResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string()
})

