/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Booker Platform API
 * API of the Booker hotel, the test object for the DeTesters Playwright training. Log in with `admin` / `password123` or `user` / `password123` and click Authorize.
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod';



/**
 * Sorted by room number.
 * @summary List all rooms
 */
export const getApiRoomsResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.array(zod.object({
  "id": zod.string(),
  "number": zod.string(),
  "type": zod.enum(['STANDARD', 'DELUXE', 'SUITE']),
  "price": zod.number().describe('Price per night'),
  "capacity": zod.number(),
  "amenities": zod.array(zod.string()),
  "status": zod.enum(['AVAILABLE', 'OCCUPIED', 'MAINTENANCE']),
  "featured": zod.boolean().describe('Shown on the home page'),
  "imageUrl": zod.string().nullable().describe('Photo uploaded with `POST /api/rooms/{id}/image`'),
  "position": zod.number().describe('Order in the admin room list; set with `PUT /api/rooms/order`'),
  "createdAt": zod.string().datetime(),
  "updatedAt": zod.string().datetime()
}))
})

/**
 * @summary Create a room (admin only)
 */
export const postApiRoomsBodyNumberMax = 20;
export const postApiRoomsBodyPriceMin = 0;
export const postApiRoomsBodyCapacityMax = 10;


export const postApiRoomsBody = zod.object({
  "number": zod.string().max(postApiRoomsBodyNumberMax).optional(),
  "type": zod.enum(['STANDARD', 'DELUXE', 'SUITE']).optional(),
  "price": zod.number().min(postApiRoomsBodyPriceMin).optional(),
  "capacity": zod.number().min(1).max(postApiRoomsBodyCapacityMax).optional(),
  "amenities": zod.array(zod.string()).optional(),
  "status": zod.enum(['AVAILABLE', 'OCCUPIED', 'MAINTENANCE']).optional(),
  "featured": zod.boolean().optional()
}).and(zod.object({

}))

/**
 * Used by drag and drop in the admin room list. Rooms get positions 1..n in the given order. Ids of rooms that no longer exist are skipped, so a room deleted in the meantime does not block the new order.
 * @summary Save the room order (admin only)
 */
export const putApiRoomsOrderBody = zod.object({
  "roomIds": zod.array(zod.string())
})

export const putApiRoomsOrderResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.array(zod.object({
  "id": zod.string(),
  "number": zod.string(),
  "type": zod.enum(['STANDARD', 'DELUXE', 'SUITE']),
  "price": zod.number().describe('Price per night'),
  "capacity": zod.number(),
  "amenities": zod.array(zod.string()),
  "status": zod.enum(['AVAILABLE', 'OCCUPIED', 'MAINTENANCE']),
  "featured": zod.boolean().describe('Shown on the home page'),
  "imageUrl": zod.string().nullable().describe('Photo uploaded with `POST /api/rooms/{id}/image`'),
  "position": zod.number().describe('Order in the admin room list; set with `PUT /api/rooms/order`'),
  "createdAt": zod.string().datetime(),
  "updatedAt": zod.string().datetime()
}))
})

/**
 * @summary Get a room
 */
export const getApiRoomsIdResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "id": zod.string(),
  "number": zod.string(),
  "type": zod.enum(['STANDARD', 'DELUXE', 'SUITE']),
  "price": zod.number().describe('Price per night'),
  "capacity": zod.number(),
  "amenities": zod.array(zod.string()),
  "status": zod.enum(['AVAILABLE', 'OCCUPIED', 'MAINTENANCE']),
  "featured": zod.boolean().describe('Shown on the home page'),
  "imageUrl": zod.string().nullable().describe('Photo uploaded with `POST /api/rooms/{id}/image`'),
  "position": zod.number().describe('Order in the admin room list; set with `PUT /api/rooms/order`'),
  "createdAt": zod.string().datetime(),
  "updatedAt": zod.string().datetime()
})
})

/**
 * Partial update; only the fields you send are changed.
 * @summary Update a room (admin only)
 */
export const putApiRoomsIdBodyNumberMax = 20;
export const putApiRoomsIdBodyPriceMin = 0;
export const putApiRoomsIdBodyCapacityMax = 10;


export const putApiRoomsIdBody = zod.object({
  "number": zod.string().max(putApiRoomsIdBodyNumberMax).optional(),
  "type": zod.enum(['STANDARD', 'DELUXE', 'SUITE']).optional(),
  "price": zod.number().min(putApiRoomsIdBodyPriceMin).optional(),
  "capacity": zod.number().min(1).max(putApiRoomsIdBodyCapacityMax).optional(),
  "amenities": zod.array(zod.string()).optional(),
  "status": zod.enum(['AVAILABLE', 'OCCUPIED', 'MAINTENANCE']).optional(),
  "featured": zod.boolean().optional()
})

export const putApiRoomsIdResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "id": zod.string(),
  "number": zod.string(),
  "type": zod.enum(['STANDARD', 'DELUXE', 'SUITE']),
  "price": zod.number().describe('Price per night'),
  "capacity": zod.number(),
  "amenities": zod.array(zod.string()),
  "status": zod.enum(['AVAILABLE', 'OCCUPIED', 'MAINTENANCE']),
  "featured": zod.boolean().describe('Shown on the home page'),
  "imageUrl": zod.string().nullable().describe('Photo uploaded with `POST /api/rooms/{id}/image`'),
  "position": zod.number().describe('Order in the admin room list; set with `PUT /api/rooms/order`'),
  "createdAt": zod.string().datetime(),
  "updatedAt": zod.string().datetime()
})
})

/**
 * @summary Delete a room (admin only)
 */
export const deleteApiRoomsIdResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string()
})

/**
 * PNG, JPEG, GIF or WebP; at most 2 MB. Replaces the previous photo.
 * @summary Upload a room photo (admin only)
 */
export const postApiRoomsIdImageBody = zod.object({
  "image": zod.instanceof(File)
})

export const postApiRoomsIdImageResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "id": zod.string(),
  "number": zod.string(),
  "type": zod.enum(['STANDARD', 'DELUXE', 'SUITE']),
  "price": zod.number().describe('Price per night'),
  "capacity": zod.number(),
  "amenities": zod.array(zod.string()),
  "status": zod.enum(['AVAILABLE', 'OCCUPIED', 'MAINTENANCE']),
  "featured": zod.boolean().describe('Shown on the home page'),
  "imageUrl": zod.string().nullable().describe('Photo uploaded with `POST /api/rooms/{id}/image`'),
  "position": zod.number().describe('Order in the admin room list; set with `PUT /api/rooms/order`'),
  "createdAt": zod.string().datetime(),
  "updatedAt": zod.string().datetime()
})
})

/**
 * @summary Remove the room photo (admin only)
 */
export const deleteApiRoomsIdImageResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "id": zod.string(),
  "number": zod.string(),
  "type": zod.enum(['STANDARD', 'DELUXE', 'SUITE']),
  "price": zod.number().describe('Price per night'),
  "capacity": zod.number(),
  "amenities": zod.array(zod.string()),
  "status": zod.enum(['AVAILABLE', 'OCCUPIED', 'MAINTENANCE']),
  "featured": zod.boolean().describe('Shown on the home page'),
  "imageUrl": zod.string().nullable().describe('Photo uploaded with `POST /api/rooms/{id}/image`'),
  "position": zod.number().describe('Order in the admin room list; set with `PUT /api/rooms/order`'),
  "createdAt": zod.string().datetime(),
  "updatedAt": zod.string().datetime()
})
})

