/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Booker Platform API
 * API of the Booker hotel, the test object for the DeTesters Playwright training. Log in with `admin` / `password123` or `user` / `password123` and click Authorize.
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod';



/**
 * Removes all users, rooms, bookings, messages, reports and branding, runs the seed again
and turns all trainer flags off.

 * @summary Reset the database to the seed data
 */
export const postApiTestingResetResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "users": zod.number(),
  "rooms": zod.number(),
  "bookings": zod.number(),
  "messages": zod.number()
})
})

/**
 * Creates users, rooms and bookings for one namespace (for example one Playwright worker).
Usernames become `{namespace}-{username}` and room numbers `{namespace}-{number}`.
Users and rooms that already exist are updated, so calling this twice is safe.
Bookings refer to users and rooms by their name in this request (or an existing username / room number)
and are created without validation, so you can create past bookings or any status.

 * @summary Create namespaced test data
 */
export const postApiTestingSeedBodyNamespaceRegExp = new RegExp('^[A-Za-z0-9_]{1,30}$');
export const postApiTestingSeedBodyUsersItemPasswordDefault = "password123";export const postApiTestingSeedBodyUsersItemRoleDefault = "USER";export const postApiTestingSeedBodyRoomsItemStatusDefault = "AVAILABLE";export const postApiTestingSeedBodyBookingsItemStatusDefault = "CONFIRMED";

export const postApiTestingSeedBody = zod.object({
  "namespace": zod.string().regex(postApiTestingSeedBodyNamespaceRegExp),
  "users": zod.array(zod.object({
  "username": zod.string(),
  "password": zod.string().default(postApiTestingSeedBodyUsersItemPasswordDefault),
  "email": zod.string().optional().describe('Default: `{namespace}-{username}@booker.test`'),
  "role": zod.enum(['USER', 'ADMIN']).default(postApiTestingSeedBodyUsersItemRoleDefault)
})).optional(),
  "rooms": zod.array(zod.object({
  "number": zod.string(),
  "type": zod.enum(['STANDARD', 'DELUXE', 'SUITE']),
  "price": zod.number(),
  "capacity": zod.number(),
  "amenities": zod.array(zod.string()).optional(),
  "status": zod.enum(['AVAILABLE', 'OCCUPIED', 'MAINTENANCE']).default(postApiTestingSeedBodyRoomsItemStatusDefault)
})).optional(),
  "bookings": zod.array(zod.object({
  "user": zod.string(),
  "room": zod.string(),
  "checkIn": zod.string().datetime(),
  "checkOut": zod.string().datetime(),
  "status": zod.enum(['PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED']).default(postApiTestingSeedBodyBookingsItemStatusDefault)
})).optional()
})

/**
 * @summary Delete all test data of a namespace
 */
export const deleteApiTestingNamespaceNamespacePathNamespaceRegExp = new RegExp('^[A-Za-z0-9_]{1,30}$');


export const deleteApiTestingNamespaceNamespaceParams = zod.object({
  "namespace": zod.string().regex(deleteApiTestingNamespaceNamespacePathNamespaceRegExp)
})

export const deleteApiTestingNamespaceNamespaceResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "users": zod.number(),
  "rooms": zod.number(),
  "bookings": zod.number(),
  "messages": zod.number()
})
})

/**
 * @summary Get the enabled and available trainer flags
 */
export const getApiTestingFlagsResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "enabled": zod.array(zod.string()),
  "available": zod.array(zod.string())
})
})

/**
 * Replaces the enabled flags for all requests. A single request can also enable flags with the
`x-booker-flags` header, for example `x-booker-flags: slow-rooms,random-order`.
`POST /api/testing/reset` turns all flags off.

 * @summary Set the enabled trainer flags
 */
export const putApiTestingFlagsBody = zod.object({
  "flags": zod.array(zod.enum(['slow-rooms', 'flaky-booking', 'stale-list', 'bug-a11y', 'bug-visual', 'bug-price', 'bug-auth', 'random-order', 'popup-cookie']))
})

export const putApiTestingFlagsResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "enabled": zod.array(zod.string()),
  "available": zod.array(zod.string())
})
})

